server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:usersDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
application:
  users:
    error:
      message:
        "7002": "lo sentimos, no hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente."
        "7000": "tu tiempo de conexión ha expirado. Por tu seguridad debes ingresar nuevamente."
        "7003": "No se tiene un resultado de la consulta usuarios"
        "7004": "Los parametros de entrada son incorrectos"
        "7005": "El correo ya registrado."
        "7006": "Credenciales incorrectas o token incorrecto"
        "7007": "Formato del correo incorrecto"
        "7008": "Formato del password incorrecto"
jwt:
  secret: 'jpizarroaguado@gmail.com'
password:
  patternpass: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,20}$"